name: vorex_app
description: VOREX — маркетплейс игровых товаров и цифровых подписок
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
